name: Release

on:
  workflow_dispatch:

jobs:

  build_and_release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: task.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}